name: "Notion On Commit"
description: "Update page property on commit"
branding:
  icon: book-open
  color: white
inputs:
  gh-username:
    description: "GitHub username of user who has access to the repository"
    required: true
  gh-token:
    description: "GitHub access token of user who has access to the repository"
    required: true
  notion-key:
    description: "Notion Integration Secret Key"
    required: true
  notion-property-name:
    description: "Notion Page property to be updated"
    required: true
  notion-property-type:
    description: "Type of Notion Page property"
    required: false
  notion-update-value:
    description: "New value for Notion page property"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
